---
- name: Update apt
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        autoclean: true
